// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.12.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables

import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_TiberiusClientTokioUtilCompatCompatTokioNetTcpStreamPtr =>
          wire.rust_arc_decrement_strong_count_RustOpaque_stdsyncRwLocktiberiusClienttokio_utilcompatCompattokionetTcpStream;

  @protected
  TiberiusClientTokioUtilCompatCompatTokioNetTcpStream
      dco_decode_Auto_Owned_RustOpaque_stdsyncRwLocktiberiusClienttokio_utilcompatCompattokionetTcpStream(
          dynamic raw);

  @protected
  TiberiusClientTokioUtilCompatCompatTokioNetTcpStream
      dco_decode_RustOpaque_stdsyncRwLocktiberiusClienttokio_utilcompatCompattokionetTcpStream(
          dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  DataInfo dco_decode_data_info(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  InitData dco_decode_init_data(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<DataInfo> dco_decode_list_data_info(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  int dco_decode_usize(dynamic raw);

  @protected
  TiberiusClientTokioUtilCompatCompatTokioNetTcpStream
      sse_decode_Auto_Owned_RustOpaque_stdsyncRwLocktiberiusClienttokio_utilcompatCompattokionetTcpStream(
          SseDeserializer deserializer);

  @protected
  TiberiusClientTokioUtilCompatCompatTokioNetTcpStream
      sse_decode_RustOpaque_stdsyncRwLocktiberiusClienttokio_utilcompatCompattokionetTcpStream(
          SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  DataInfo sse_decode_data_info(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  InitData sse_decode_init_data(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<DataInfo> sse_decode_list_data_info(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_usize(SseDeserializer deserializer);

  @protected
  String cst_encode_String(String raw) {
    return raw;
  }

  @protected
  List<dynamic> cst_encode_data_info(DataInfo raw) {
    return [
      cst_encode_String(raw.sn),
      cst_encode_String(raw.cusPn),
      cst_encode_String(raw.sntitle),
      cst_encode_String(raw.inName),
      cst_encode_String(raw.inloss1),
      cst_encode_String(raw.reloss1),
      cst_encode_String(raw.outName),
      cst_encode_String(raw.inloss2),
      cst_encode_String(raw.reloss2),
      cst_encode_i_32(raw.printNum)
    ];
  }

  @protected
  List<dynamic> cst_encode_init_data(InitData raw) {
    return [
      cst_encode_String(raw.librarieId),
      cst_encode_list_String(raw.printers),
      cst_encode_list_String(raw.btws),
      cst_encode_bool(raw.sqlstatus)
    ];
  }

  @protected
  List<dynamic> cst_encode_list_String(List<String> raw) {
    return raw.map(cst_encode_String).toList();
  }

  @protected
  List<dynamic> cst_encode_list_data_info(List<DataInfo> raw) {
    return raw.map(cst_encode_data_info).toList();
  }

  @protected
  Uint8List cst_encode_list_prim_u_8_strict(Uint8List raw) {
    return raw;
  }

  @protected
  PlatformPointer
      cst_encode_Auto_Owned_RustOpaque_stdsyncRwLocktiberiusClienttokio_utilcompatCompattokionetTcpStream(
          TiberiusClientTokioUtilCompatCompatTokioNetTcpStream raw);

  @protected
  PlatformPointer
      cst_encode_RustOpaque_stdsyncRwLocktiberiusClienttokio_utilcompatCompattokionetTcpStream(
          TiberiusClientTokioUtilCompatCompatTokioNetTcpStream raw);

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  int cst_encode_i_32(int raw);

  @protected
  int cst_encode_u_32(int raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  int cst_encode_usize(int raw);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_stdsyncRwLocktiberiusClienttokio_utilcompatCompattokionetTcpStream(
          TiberiusClientTokioUtilCompatCompatTokioNetTcpStream self,
          SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_stdsyncRwLocktiberiusClienttokio_utilcompatCompattokionetTcpStream(
          TiberiusClientTokioUtilCompatCompatTokioNetTcpStream self,
          SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_data_info(DataInfo self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_init_data(InitData self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_data_info(List<DataInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire extends BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void dart_fn_deliver_output(int call_id, PlatformGeneralizedUint8ListPtr ptr_,
          int rust_vec_len_, int data_len_) =>
      wasmModule.dart_fn_deliver_output(
          call_id, ptr_, rust_vec_len_, data_len_);

  void wire_client(NativePortType port_, String sql) =>
      wasmModule.wire_client(port_, sql);

  void wire_do_print(NativePortType port_, String sn, String sql, String id,
          String btw, String printer, int float) =>
      wasmModule.wire_do_print(port_, sn, sql, id, btw, printer, float);

  void wire_get_libraries(NativePortType port_) =>
      wasmModule.wire_get_libraries(port_);

  void wire_init_all(NativePortType port_, String sql) =>
      wasmModule.wire_init_all(port_, sql);

  void wire_init_app(NativePortType port_) => wasmModule.wire_init_app(port_);

  void wire_load_btws(NativePortType port_, String id) =>
      wasmModule.wire_load_btws(port_, id);

  void wire_load_printers(NativePortType port_) =>
      wasmModule.wire_load_printers(port_);

  void wire_run_query(NativePortType port_, String sn, String sql) =>
      wasmModule.wire_run_query(port_, sn, sql);

  void wire_sql_init(NativePortType port_, String sql) =>
      wasmModule.wire_sql_init(port_, sql);

  void wire_updata(NativePortType port_, List<dynamic> list, String sql) =>
      wasmModule.wire_updata(port_, list, sql);

  void rust_arc_increment_strong_count_RustOpaque_stdsyncRwLocktiberiusClienttokio_utilcompatCompattokionetTcpStream(
          dynamic ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_stdsyncRwLocktiberiusClienttokio_utilcompatCompattokionetTcpStream(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_stdsyncRwLocktiberiusClienttokio_utilcompatCompattokionetTcpStream(
          dynamic ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_stdsyncRwLocktiberiusClienttokio_utilcompatCompattokionetTcpStream(
              ptr);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
class RustLibWasmModule implements WasmModule {
  @override
  external Object /* Promise */ call([String? moduleName]);

  @override
  external RustLibWasmModule bind(dynamic thisArg, String moduleName);

  external void dart_fn_deliver_output(int call_id,
      PlatformGeneralizedUint8ListPtr ptr_, int rust_vec_len_, int data_len_);

  external void wire_client(NativePortType port_, String sql);

  external void wire_do_print(NativePortType port_, String sn, String sql,
      String id, String btw, String printer, int float);

  external void wire_get_libraries(NativePortType port_);

  external void wire_init_all(NativePortType port_, String sql);

  external void wire_init_app(NativePortType port_);

  external void wire_load_btws(NativePortType port_, String id);

  external void wire_load_printers(NativePortType port_);

  external void wire_run_query(NativePortType port_, String sn, String sql);

  external void wire_sql_init(NativePortType port_, String sql);

  external void wire_updata(
      NativePortType port_, List<dynamic> list, String sql);

  external void
      rust_arc_increment_strong_count_RustOpaque_stdsyncRwLocktiberiusClienttokio_utilcompatCompattokionetTcpStream(
          dynamic ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_stdsyncRwLocktiberiusClienttokio_utilcompatCompattokionetTcpStream(
          dynamic ptr);
}
